---

- name: Install Docker CE 
  yum:
    name: ["python-pip", "docker", "device-mapper-libs", "device-mapper-event-libs"]
    state: present

- name: Install pip
  pip:
    name: docker
    version: 3.1.4

- name: Install pip docker-compose library
  pip:
    name: docker-compose
    version: 1.20.1

- name: Install pip dependencies
  pip:
    name: ["docker-pycreds", "dockerpty"]
